### ISSUE TITLE
Provide builds with libvirt support

### ISSUE THREAD

**Issue by fabiand** [openshift/installer#1213]
KubeVirt plans ot be running on Origin 4. In order to do so we need to setup an OCP 4 environment, the installer looks like the right way to set it up.

Please provide installer builds with libvirt support in order to avoid that we have to perform those builds in our CI.

**Comment by wking** [comment]
This is [an existing release issue][1], not an installer issue.

/close

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1666561

**Comment by fabiand** [comment]
I'm not sure why this issue shoul dbe a dupe of the linked bug. Thanks AI
...

**Comment by wking** [comment]
The installer team doesn't build update-payloads, we just pin what ART pushes to quay.io.  Until they push the libvirt machine-API image too (the linked issue), pinned installer releases will have issues on libvirt with quay.io payloads.

There's a separate issue of "once ART fixes the update payloads, will released installer binaries include libvirt support".  That's wont-fix, because libvirt is dev-only best-effort (more in #955).  But it's easy to work around,  just check out the released tag and [build yourself with `TAGS=libvirt`][1].

[1]: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#build-and-run-the-installer
