### ISSUE TITLE
RFE: add versioning to pull-secret file and check at installer

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/installer#1321]
# Version

```console
$ ./openshift-install version
./openshift-install v0.13.0
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

I've been testing `openshift-installer` since version v0.8.0, using the same `pull-secret.txt` that I downloaded at that time. Due #1320, i discovered that the schema for the `pull-secret` has changed to include more authentication credentials.

# What you expected to happen?

We should start versioning the `pull-secret`, so the `openshift-installer` could start checking if the file reflects the last schema and expected content. As an example, the file should look like:

```json
{
    "version": 1.0,
    "auths": {
        "cloud.openshift.com": {
            "auth": "XXX",
            "email": "johndoe@example.com"
        },
        "quay.io": {
            "auth": "XXX",
            "email": "johndoe@example.com"
        },
        "registry.connect.redhat.com": {
            "auth": "XXX",
            "email": "johndoe@example.com"
        },
        "registry.redhat.io": {
            "auth": "XXX",
            "email": "johndoe@example.com"
        }
    }
}
```

**Comment by wking** [comment]
> Due #1320, i discovered that the schema for the `pull-secret` has changed to include more authentication credentials.

That's a data change, not a schema change.  Validating the data as sufficient is hard, because it depends on what you end up installing (more in #901).  #1286 will give us some installer-side validation, but it would not have prevented #1320.

On the schema side, I'm fine without a version, since the format has been backwards compatible for years.  But I'm not strongly against explicit versioning either.  It's probably better to have that discussion upstream in containers/image though.

**Comment by abhinavdahiya** [comment]
This is not somethings installer can fix.

/close
