### ISSUE TITLE
Is there a hindrance to creating a version for Windows?

### ISSUE THREAD

**Issue by DonSchenck** [openshift/installer#1586]
Is there a reason why a Windows version cannot be created? Are there plans?

**Comment by wking** [comment]
My main concern would be setting up CI for the Windows builds.  I expect it will work once we get better libvirt decoupling to avoid:

```console
$ GOOS=windows SKIP_GENERATION=y OUTPUT=bin/openshift-install-windows hack/build.sh
...
# github.com/openshift/installer/pkg/tfvars/libvirt
pkg/tfvars/libvirt/cache.go:126:8: undefined: unix.Flock
pkg/tfvars/libvirt/cache.go:126:36: undefined: unix.LOCK_EX
pkg/tfvars/libvirt/cache.go:131:11: undefined: unix.Flock
pkg/tfvars/libvirt/cache.go:131:39: undefined: unix.LOCK_UN
```

and anything similar that that error is masking.

**Comment by kai-uwe-rommel** [comment]
Hi, I'm currently writing scripts to fully automate deployment of OpenShift (and OKD) 4 into corporate vSphere environments. Our customers usually run their DHCP and DNS on Windows servers so I decided to use PowerShell for vSphere (PowerCLI) and DHCP/DNS server configuration. To avoid platform switching in the process of a cluster deployment it would be of great help if not only the "oc" client but also "openshift-install" were available for Windows. To me it looks like this should not be too difficult as it does not seem to perform any *nix specific black magic but would just need to be compiled for Windows. Or is there a specific reason why not? Since it is written in Go, it should compile for Windows? I can perhaps try myself but I do not have experience with Go...
BTW, I would only need support for creating the configs for on-premise vSphere installations, no public cloud or OpenStack support.
