### ISSUE TITLE
Migrating from 3x Openshift installs

### ISSUE THREAD

**Issue by magick93** [openshift/installer#1634]
Hello

I'm interested to learn more about the OpenShift 4 installer, and how different, or similar, it is from previous ansible based approaches to installing Openshift.

We have learned a lot about installing OpenShift, and have, over the years, customized our openshift ansible inventory file. 

Will we still be able to use this?

Does the new installer still use ansible?

Thanks

**Comment by wking** [comment]
> I'm interested to learn more about the OpenShift 4 installer, and how different, or similar, it is from previous ansible based approaches to installing Openshift.

The v4 installer is a descendant of [the Tectonic Installer][1], so it doesn't share code with the v3 Ansible installer.  v4 retains [some Ansible tools][2], primarily to support folks who want to bring their own RHEL-ish instead of using RHCOS machines in their v4 cluster.

> We have learned a lot about installing OpenShift, and have, over the years, customized our openshift ansible inventory file.
>
> Will we still be able to use this?

Not out of the box.  The v4 installer focuses on doing the bare minimum needed to get a v4 cluster off the ground, after which you can customize all sorts of things as day-2 operations.  So I expect most of your customizations and tuning will migrate out of Ansible and into Kubernetes/OpenShift manifests.  And the point of the operator approach is that operators can collect this sort of operational wisdom in central locations that can be shared by all Kubernetes/OpenShift cluster admins, vs. keeping install-time wisdom in in-house files.  So it will take some legwork on your part to bring your wisdom into your v4 cluster (e.g. via pull requests to operators), but once it lands everyone benefits and you don't have to worry about continuing to carry it locally and eventually porting into OpenShift v5 or whatever comes next ;).

I'm going to close this, because I don't see any actionable installer changes coming out of it, but feel free to continue the discussion if you have particular bits of customization you're interested in, or if you do see places where the installer could help support you (doesn't mean we can do them, but it doesn't hurt to talk them through ;).

/close

[1]: http://github.com/coreos/tectonic-installer/
[2]: https://github.com/openshift/openshift-ansible
