### ISSUE TITLE
Allow new lines in  Pull Secret

### ISSUE THREAD

**Issue by kadel** [openshift/installer#1644]
It would be easier if installer would accept Pull Secret  that is formatted (includes new lines).

Currently all  new lines has to be stripped before pasting, otherwise installer complains.

```
? Pull Secret [? for help] *
X Sorry, your reply was invalid: unexpected end of JSON input
X Sorry, your reply was invalid: invalid character 'd' in literal false (expecting 'a')
X Sorry, your reply was invalid: invalid character 'a' looking for beginning of value
````

`openshift-installer` build from 8c607f66662f8e35570960484612d0589c26b654

**Comment by wking** [comment]
> It would be easier if installer would accept Pull Secret that is formatted (includes new lines).

I'm not aware of multi-line password support in [our wizard library][1].  If/when it grows that support, we could certainly move to it.  But since multi-line passwords seem like a niche case, and the pull secrets you can download or copy from [here][1] are already single lines, I'm going to close this.  Feel free to continue discussion if you feel like I'm missing a case for an open issue.

/close

[1]: https://cloud.openshift.com/clusters/install

[1]: https://github.com/AlecAivazis/survey

**Comment by kadel** [comment]
> I'm not aware of multi-line password support in [our wizard library](https://github.com/AlecAivazis/survey). If/when it grows that support, we could certainly move to it. But since multi-line passwords seem like a niche case,

multi-line password is a niche case, but here we don't have pain password but JSON struct 

> and the pull secrets you can download or copy from [here](https://cloud.openshift.com/clusters/install) are already single lines, I'm going to close this. Feel free to continue discussion if you feel like I'm missing a case for an open issue.

Yes pull secret download from https://cloud.openshift.com/clusters/install is a single line, but if you do `oc registry login --to ...` it will produce multi-line json file, then you have to go through troubles of removing new lines before you can use this :-( 

It is not a huge deal, but it is a little bit annoying.

**Comment by wking** [comment]
> ... but if you do `oc registry login --to ...` it will produce multi-line json file...

We can probably get `oc` an option for compact output.  In the meantime, `jq -c .` is a handy filter :).
