### ISSUE TITLE
Duplicate nodes joining a cluster

### ISSUE THREAD

**Issue by rajatchopra** [openshift/installer#1874]
# Version

![openshift-install-version](https://user-images.githubusercontent.com/982221/59804513-64348980-92a3-11e9-8220-9ea35216a70a.png)

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Node registered twice over. Once with a hostname 'localhost.localdomain' (probably when its booting up?). Then with the correct hostname (worker-0). See that the IP address is the same (10.136.6.41).

![openshift-get-nodes](https://user-images.githubusercontent.com/982221/59804509-5da61200-92a3-11e9-8c77-7a1fb1464785.png)

# What you expected to happen?

The node has only one object created for itself.

# How to reproduce it (as minimally and precisely as possible)?

Just the regular openshift install process.

**Comment by abhinavdahiya** [comment]
The platform mentioned here is `AWS` but the node names indicate towards a non-installer-provisioned cluster where the hostnames were either manually supplied rather than the `Just the regular openshift install process.`?

Can you include the steps that were taken for this setup and also include the `.openshift_install.log` _make sure you remove any personal or secret data_

Also if the cloud provider is correctly set, kube-controller-manager has logic to remove the stale node object by making sure that the backing instance is actually gone and the node object is no longer required. Maybe should open bug with kubernetes upstream is that's not happening.

**Comment by rajatchopra** [comment]
@abhinavdahiya You are right. This was not on AWS. But a baremetal deployment.

@SteveNashNVIDIA Any more info you happen to have?

**Comment by SteveNashNVIDIA** [comment]
All the nodes were deployed together, but after ~1 week or so, the node that is duplicated (worker-0) was redeployed.  The hostname is provided via the DNS nameserver.  Attaching log.

[openshift_install.log](https://github.com/openshift/installer/files/3312332/openshift_install.log)

**Comment by abhinavdahiya** [comment]
> All the nodes were deployed together, but after ~1 week or so, the node that is duplicated (worker-0) was redeployed.

So this doesn't look like an installation problem. @rajatchopra @SteveNashNVIDIA can you open a bugzilla using the link https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform so that we can get the OS and Machine Config Operator teams involved as they own the configuration of the hosts... ?
