### ISSUE TITLE
Question: Can installer be used with xhyve/virtualbox hypervisors?

### ISSUE THREAD

**Issue by cmoulliard** [openshift/installer#201]
Question : Can openshift installer (tectonic) be used to install a all-in-one cluster using with xhyve/virtualbox hypervisor  ?

**Comment by wking** [comment]
At the moment we're just AWS and libvirt.  Libvirt can handle [a number of hypervisors][1], [including VirtualBox][2].  I'm not sure how portable we are between those hypervisors.  Maybe we work on all of them, maybe not.  I'm only aware of folks testing with [the QEMU backend][3] (which we hope to cover with CI soon).  To test this out, you'll want to toggle [the libvirt URI][4] when working through [the libvirt procedure][5].

[1]: https://libvirt.org/drivers.html#hypervisor
[2]: https://libvirt.org/drvvbox.html
[3]: https://libvirt.org/drvqemu.html
[4]: https://github.com/openshift/installer/blob/f2e6b3ed56aa114cd263369fd626d6b0e493e6ed/examples/tectonic.libvirt.yaml#L14
[5]: https://github.com/openshift/installer/blob/f2e6b3ed56aa114cd263369fd626d6b0e493e6ed/Documentation/dev/libvirt-howto.md

**Comment by cmoulliard** [comment]
Many thanks. I will have a look. Will openshift installer be used to perform `oc cluster up` ?

**Comment by wking** [comment]
> Will openshift installer be used to perform `oc cluster up`?

Maybe eventually?  For now, the next-gen command is [`openshift-install`][1] (still a work in progress).  @smarterclayton or @aaronlevy may be able to weigh in on `oc` integration plans.  But if there's much to say on this point, it's probably worth spinning off into its own issue.

[1]: https://github.com/openshift/installer/tree/1bdd57e3418fbf31ec7a3d06260fb9431f8b78ee/cmd/openshift-install

**Comment by smarterclayton** [comment]
@jwforres as well, this isn’t our primary focus but we will come back to it soon and try to find a path that minimizes the wrong sorts of install duplication.

**Comment by jwforres** [comment]
Last week I tried going down the path @wking [suggests above](https://github.com/openshift/installer/issues/201#issuecomment-418886919) and hit an issue with libvirt hanging trying to connect to the vbox uri, if someone gets it to connect successfully let me know.

I don't recommend trying the alternate path of making libvirt + qemu work on a Mac, [libvirt is not set up to work with qemu](https://github.com/Homebrew/homebrew-core/blob/08f577940076089363abc7f789067f3549d9c0e2/Formula/libvirt.rb#L41) in the mac package managers (like homebrew). I wound up re-compiling from source. It was a rabbit hole and in the end only got me a few steps further in the installer before it broke again on another piece around networking that wasn't getting compiled in to the homebrew version of libvirt.

**Comment by jwforres** [comment]
As far as long term about how the installer and oc relate, these are discussions we are absolutely having, and we don't want to end up with 3 or 4 installers. We need to find the right way to tie oc cluster up into what the new operator-based installation model can do for us.

**Comment by rabugopsl** [comment]
I’m working on a CentOS7 container which might do the trick. I’m having issues with some libvirt resources, but I hope I can have those sorted out to have a fully functional environment for everyone.

**Comment by crawford** [comment]
VirtualBox is not supported by the installer. In order for a hypervisor to be supported, libvirt _and_ Ignition must support it. Right now, Ignition technically supports VirtualBox, but the implementation is subpar and was rushed due to product demands.

VirtualBox needs support for user-provided data (similar to VMware's Guest Properties mechanism). Until it is added, I'm going to push back pretty hard on supporting that hypervisor.

As for xhyve, does it have the mechanism I've described above? If so, support for it will need to be added to Ignition and then we can try to enable it in the installer. It's worth noting that libvirt on OS X doesn't support networking, which is the bigger roadblock in my mind. We need to be able to do basic DNS and DHCP manipulation in order to properly bring up a cluster.

**Comment by ironcladlou** [comment]
I got the installer working on OSX using VT-x nested virtualization from a Fedora 28 VM using Fusion 11 Pro. I put my experiment notes [in this gist](https://gist.github.com/ironcladlou/56b5070961ee1e21ee105732d75767cd) in case anybody's curious.

**Comment by gbraad** [comment]
> `oc cluster up`

This has officially been removed to focus efforts on installer to become the new way to standup a possible all in one

**Comment by gbraad** [comment]
Great to see, but I have to be honest, nested is not the way forward. We need to be able to use native hypervisors as the overhead gives a noticeable performance degradation. It works for development of the installer, but not for use of the cluster

**Comment by gbraad** [comment]
@crawford to most likely target that meets the requirements would be HyperV. For macOS it would seem VirtualBox could be a short term solution as xhyve/hyperkit needs a whole lot more work. Anything we can help with? Pointers would be appreciated.

**Comment by LalatenduMohanty** [comment]
Nested virtualization is not something Minishift use case can use as it has the performance drawback which impacts the user experience. We need to find a way to boot the VM directly on the hypervisors.

**Comment by crawford** [comment]
@gbraad As I mentioned before, Ignition needs to support the hypervisors you intend on targeting. Adding support to Ignition tends to be pretty straightforward for hypervisors which have a decent hypervisor-to-guest bridge. The current support for VirtualBox is built on a terrible hack that was rushed through due to product demands. I would much prefer it if we used a better mechanism or committed the necessary functionality to VirtualBox to support this use case. The alternative is VMware, hich works out of the box today.

Additionally, the installer will need to support the creation of the resources for the cluster. On Linux, we use libvirt with a libvirt provider for Terraform. Unfortunately, libvirt for OSX is built without support for networking, so either libvirt will need to be updated to support networking on OSX or an alternate Terraform provider will need to be written (or found) that can manage the resources on OSX.

**Comment by DanyC97** [comment]
@crawford any reason why VMware was removed ? in tectonic you used you have a module and i suspect it was working with ignition...isn't that the case anymore ?

**Comment by crawford** [comment]
@DanyC97 the installer has been completely rewritten and shares almost nothing with the previous incarnation used by Tectonic. The installation flow is quite different from what Tectonic was doing. We will circle back and add support for new platforms eventually.

**Comment by DanyC97** [comment]
@crawford thx for taking the time to respond so quickly. Will be good if you have time to put together a lowl level flow from bootkube all the way to the operators and how each of them contribute to form the cluster

**Comment by wking** [comment]
> Will be good if you have time to put together a lowl level flow from bootkube all the way to the operators...

[This][1] is the description of the install flow.  After that, see the docs for [the cluster-version operator][2] and individual operators for details about how they are managed and what they do.

[1]: https://github.com/openshift/installer/blob/master/docs/user/overview.md#cluster-installation-process
[2]: https://github.com/openshift/cluster-version-operator/tree/master/docs/dev

**Comment by eparis** [comment]
At this time we do not intend to address this issue. We apologize for the inconvenience.

**Comment by durandom** [comment]
https://github.com/code-ready/osp4 is the current work on getting ocp4 installed locally

**Comment by gbraad** [comment]
Currently in PoC phase, but we will be adding lifecycle management tooling soon, plus support for more hypervisors. Actual support for installer-based deployments is being investigated on discussed.

**Comment by gbraad** [comment]
I suggest we update

> Support for libvirt on Mac OS is currently broken and being worked on.
[Ref](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md#macos-support-currently-broken)

to reflect the changed status.
