### ISSUE TITLE
the shipped terraform is not used when the installer is called via PATH lookup

### ISSUE THREAD

**Issue by steveeJ** [openshift/installer#210]
I ran into this issue trying to destroy a libvirt cluster:

```
$ tectonic destroy --dir=test1

Error:
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.7'

Please run at least that version of Terraform to continue.
```

Between create and destroy, I have installed terraform to my PATH.
I suspect there is something odd in the [logic to find the terraform binary][1], as removing it from PATH makes the error go away and succeed in destroying the cluster.

[1]: https://github.com/steveeJ/installer/commit/b95525199cbc7b5f8d531befe0f2b7e94a7748e5#diff-ea8bd5729880215853a015ccaaae64b1R76

**Comment by wking** [comment]
> I suggest to introduce a runtime version check and assert for >= the version that's shipped with bazel.

We ship a `terraform` binary.  I think we want to always use that one, instead of doing version comparisons.  We always recommend prepending to `PATH`:

```console
$ git grep PATH= 44bedfef
44bedfef:Documentation/dev/libvirt-howto.md:export PATH="${PWD}/installer:${PATH}"
44bedfef:README.md:    export PATH="${PWD}/installer:${PATH}"
44bedfef:modules/tectonic/resources/tectonic.sh:ASSETS_PATH="$2"
44bedfef:tests/run.sh:export PATH="${PWD}/tectonic-dev/installer:${PATH}"
```

but not everyone follows directions ;).  Should we make our tarball self-extracting by adding [a `#!/bin/sh`-based prefix][1]?  Then we can have that script ensure we always invoke the bundled `terraform`.

[1]: https://www.linuxjournal.com/node/1005818
