### ISSUE TITLE
libvirt with kvm installation failed 

### ISSUE THREAD

**Issue by ahrtr** [openshift/installer#2154]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-1353-g526edca4f6646af4bbcdf48bc2c2ee1d44d9fada
built from commit 526edca4f6646af4bbcdf48bc2c2ee1d44d9fada
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
```
[root@origin-build installer]# uname -a
Linux origin-build 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

[root@origin-build ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

# What happened?
```
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Still waiting for the Kubernetes API: Get https://api.test1.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: connection refused 
DEBUG Fetching "Install Config"...                 
DEBUG Loading "Install Config"...                  
DEBUG   Loading "SSH Key"...                       
DEBUG   Using "SSH Key" loaded from state file     
DEBUG   Loading "Base Domain"...                   
DEBUG     Loading "Platform"...                    
DEBUG     Using "Platform" loaded from state file  
DEBUG   Using "Base Domain" loaded from state file 
DEBUG   Loading "Cluster Name"...                  
DEBUG     Loading "Base Domain"...                 
DEBUG   Using "Cluster Name" loaded from state file 
DEBUG   Loading "Pull Secret"...                   
DEBUG   Using "Pull Secret" loaded from state file 
DEBUG   Loading "Platform"...                      
DEBUG Using "Install Config" loaded from state file 
DEBUG Reusing previously-fetched "Install Config"  
INFO Pulling debug logs from the bootstrap machine 
ERROR failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: dial tcp: lookup test1-zfgrt-bootstrap on 9.0.149.140:53: no such host 
FATAL waiting for Kubernetes API: context deadline exceeded 

```

# What you expected to happen?
I expected to see successful result.

# How to reproduce it (as minimally and precisely as possible)?
I just followed the guide as below,
https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md

Note that I did not configure the NetworkManager per the guide, because the /etc/resolv.conf will be overwritten with only "nameserver 127.0.0.1" each time I configured NetworkManager per the guide.

**Comment by zeenix** [comment]
> Note that I did not configure the NetworkManager per the guide,

That's the issue then. You must do those things for DNS etc to work.

> because the /etc/resolv.conf will be overwritten with only "nameserver 127.0.0.1" each time I configured NetworkManager per the guide.

The guide says nothing about `/etc/resolv.conf` so not sure what you mean here.

/close

**Comment by ahrtr** [comment]
I ran int exactly the same issue after configuring NetworkManager, so just raised a new issue, 
https://github.com/openshift/installer/issues/2157

**Comment by sujoykr1** [comment]
@ahrtr  I am facing similar issue after following https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md
No clue what went wrong.  Please let me know how did you resolved this. 


`DEBUG Still waiting for the Kubernetes API: Get "https://api.test1.tt.testing:6443/version?timeout=32s": dial tcp 192.168.126.10:6443: connect: no route to host
DEBUG Still waiting for the Kubernetes API: Get "https://api.test1.tt.testing:6443/version?timeout=32s": dial tcp 192.168.126.11:6443: connect: no route to host
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.test1.tt.testing:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 192.168.126.11:6443: connect: no route to host
DEBUG Fetching Bootstrap SSH Key Pair...
DEBUG Loading Bootstrap SSH Key Pair...
DEBUG Using Bootstrap SSH Key Pair loaded from state file
DEBUG Reusing previously-fetched Bootstrap SSH Key Pair
DEBUG Fetching Install Config...
DEBUG Loading Install Config...
DEBUG   Loading SSH Key...
DEBUG   Using SSH Key loaded from state file
DEBUG   Loading Base Domain...
DEBUG     Loading Platform...
DEBUG     Using Platform loaded from state file
DEBUG   Using Base Domain loaded from state file
DEBUG   Loading Cluster Name...
DEBUG     Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Using Cluster Name loaded from state file
DEBUG   Loading Networking...
DEBUG     Loading Platform...
DEBUG   Using Networking loaded from state file
DEBUG   Loading Pull Secret...
DEBUG   Using Pull Secret loaded from state file
DEBUG   Loading Platform...
DEBUG Using Install Config loaded from state file
DEBUG Reusing previously-fetched Install Config
INFO Pulling debug logs from the bootstrap machine
DEBUG failed to parse SSH private key from "/root/.ssh/authorized_keys"
DEBUG failed to parse SSH private key from "/root/.ssh/id_ansible.pub"
DEBUG failed to parse SSH private key from "/root/.ssh/id_rsa.pub"
DEBUG failed to parse SSH private key from "/root/.ssh/known_hosts"
DEBUG Added /tmp/bootstrap-ssh537767166 to installer's internal agent
DEBUG Added /root/.ssh/id_ansible to installer's internal agent
DEBUG Added /root/.ssh/id_rsa to installer's internal agent
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: dial tcp: lookup test1-dkjv6-bootstrap.test1.tt.testing on 127.0.0.1:53: no su                  ch host
ERROR Bootstrap failed to complete: Get "https://api.test1.tt.testing:6443/version?timeout=32s": dial tcp 192.168.126.10:6443: connect: no route to host
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
ERROR Attempted to analyze the debug logs after installation failure: could not open the gather bundle: open : no such file or directory
FATAL Bootstrap failed to complete
`
