### ISSUE TITLE
Openstack: api-port detached

### ISSUE THREAD

**Issue by MartijnStraatman** [openshift/installer#2316]
# Version

```console
$ openshift-install version
./openshift-install v4.2.0
built from commit 8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:741d9b7f3256d632436e4bec8a8c2f47bb43d8285f8f44d6149c015b4e6a1a2
```

# Platform:
Openstack 14

# What happened?

During installation a port is created for the api_port. This port is attached to the FIP which is configured in the install-config.yaml  ( lbFloatingIP )

The installations times-out because the api-port is not attached to any node.  What is the use of the allowed_address_pairs on the master ports?

```
time="2019-09-05T04:34:47-04:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.os-test.<domain>:6443/version?timeout=32s: dial tcp <fip>:6443: connect: no route to host"
```

# What you expected to happen?

Reading the source code, this api-port has to be attached to one of the masters. But all masters already have a port attached.

# How to reproduce it (as minimally and precisely as possible)?

./openshift-install create cluster --dir ostest

**Comment by MartijnStraatman** [comment]
will close this issue, seems we are having a dns-issue. We will need an option to set the dns on the subnet

**Comment by tomassedovic** [comment]
Thanks. Yeah I know this looks weird, but the api-port is not supposed to be attached to any server. Its IP address is managed by Keepalived.

The allowed_address_pairs let Neutron the traffic from the api-port (and similar to dns-port and ingress-port) through even though they're not attached to any servers as far as Neutron is concerned.

You can find more details here:

https://github.com/openshift/installer/blob/master/docs/design/openstack/networking-infrastructure.md

**Comment by MartijnStraatman** [comment]
Ok, thanks. I understand the use of the allowed_address pairs. Can you maybe tell me why we can't set  dns options on the subnets? I our case our dhcp agent does not resolve outside the subnet

**Comment by tomassedovic** [comment]
@MartijnStraatman because there were so many things to implement we didn't manage it all yet :-(.

Here's a (unfortunately a little stale) PR that enables you to configure nameservers on the subnet level: https://github.com/openshift/installer/pull/2132

Unfortunately, OpenShift is now in a code freeze so it won't be merged right now. If you're okay applying that patch for now, by all means do so.

Otherwise, a option you can do is to add the nameservers to the subnet yourself after it's created by the installer.

Neither option is great, but until we open master for 4.3, they'll have to do. Sorry for the inconvenience!
