### ISSUE TITLE
All `hack/xx.sh` failed

### ISSUE THREAD

**Issue by gyliu513** [openshift/installer#2508]
I was running it in my local dev environment.

```
root@gyliu-dev1:~/go/src/github.com/openshift/installer# ./hack/go-fmt.sh
./hack/go-fmt.sh: 8: ./hack/go-fmt.sh: podman: not found
root@gyliu-dev1:~/go/src/github.com/openshift/installer# env | grep IS_CONTAINER
root@gyliu-dev1:~/go/src/github.com/openshift/installer# env | grep GOPATH
GOPATH=/root/go
```

But if I set `IS_CONTAINER` as `FALSE`, then it works.

So I think for all of the scripts, like https://github.com/openshift/installer/blob/master/hack/go-fmt.sh#L2 , should not it be as follows for all of the scripts?

```
if [ "$IS_CONTAINER" = "" ] || [ "$IS_CONTAINER" = "FALSE" ]; then
```

**Comment by abhinavdahiya** [comment]
The goal of all the scripts is to make sure all users have standard environment to reduce dependencies.
That's why these scripts are container first.

So if you install podman, so should be good to go.

The IS_CONTAINER flag is for cases where the environment is controlled outside of the script, like the CI environment.

So the scripts seem to be setup correctly.

**Comment by gyliu513** [comment]
Thanks @abhinavdahiya , I created a PR at https://github.com/openshift/installer/pull/2511 to mention `podman` was required, does this make sense?
