### ISSUE TITLE
Pivot installer to pivot ➰ into latest RHCOS

### ISSUE THREAD

**Issue by jlebon** [openshift/installer#267]
Some time soon, the installer will need to learn how to provision RHCOS using the oscontainer + [pivot](https://github.com/ashcrow/pivot) approach. One place where this is currently directly impacting us is in the MCD: https://github.com/openshift/machine-config-operator/pull/60#issuecomment-421489272. Just filing this so that it has upstream visibility and is easier to cross-ref, etc.

**Comment by wking** [comment]
Is the idea that the RHCOS image (AMI, libvirt QCOW, etc.) may be stale, and you'll want to:

```sh
pivot -r $REGISTRY/os@sha256:fdf70521df4ed1dc135d81fd3c4608574aeca45dc22d1b4e38d16630e9d6f1a7
```

or similar to something the user has configured (or which they skipped and we provided a default value for)?  That seems less efficient than just using an AMI/QCOW/... that matches your intended target, since each node would be pulling the updates after its initial boot.  But maybe I'm not understanding something; I'm very new to OSTree.

Possibly related to this is the just-landed #271 and its floating libvirt default.  Once RHCOS AMIs go public, we'll update `pkg/rhcos` to get those floating too.

**Comment by jlebon** [comment]
This is still being discussed over in https://github.com/openshift/os/issues/148, so going to close this one to keep things together.

> Is the idea that the RHCOS image (AMI, libvirt QCOW, etc.) may be stale, and you'll want to:

Kinda. The idea is that the AMI you boot up does not contain the latest RHCOS. It just contains enough to do the pivot to the latest RHCOS oscontainer.

**Comment by ashcrow** [comment]
> It just contains enough to do the pivot to the latest RHCOS oscontainer.

Specifically the AMI, or other image, will in most cases not have the latest OSTree out of the gate.
