### ISSUE TITLE
OpenShift 4.2 single node installation

### ISSUE THREAD

**Issue by vinothkumar437** [openshift/installer#2754]
Hi

Please share me any documents to install single node openshift 4.2 deployment

Thanks for the help

Regards
Vinothkumar

**Comment by abhinavdahiya** [comment]
The only single node supported deployment is libvirt https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md

otherwise all platforms require 3 control-plane and at least 2 compute like https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#machine-requirements_installing-bare-metal

**Comment by abhinavdahiya** [comment]
> The only single node supported deployment is libvirt https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md
> 
> otherwise all platforms require 3 control-plane and at least 2 compute like https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#machine-requirements_installing-bare-metal
