### ISSUE TITLE
The most minimal cluster possible

### ISSUE THREAD

**Issue by garymoon** [openshift/installer#2980]
# Version
4.3.0

# Platform:
AWS

# What happened?

For v3 we used the AIO node grouping, and it worked reasonably well for us under development workloads. In v4 there seems to be no dev-focused cluster layout we can choose from, and it's quite wasteful in terms of resources consumed (EIPs and NAT gateways are a particular pain point) & cycle time. Unfortunately, getting the UPI templates into a state resembling what we're after is likely to take even more time than we're already spending.

# What you expected to happen?

It would be great to have a similar setup to AIO for v4. In particular it would be great to see an option to avoid consuming EIPs, have the cluster in a public subnet (no NAT gateways etc), reduced spin-up time, and see some instructions on how to set up a minimal cluster for non-production workloads.

Thank you.

**Comment by abhinavdahiya** [comment]
So we allow installation to pre-existing VPCs (subnets)
https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md#cluster-scoped-properties
https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-customer-provided-subnets.md

so that should allow users to have their own non-production setup that can be reused.

also you can reduce the AZ availability for control-plane and workers https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md#machine-pools

so the installer will create simple networking..

**Comment by garymoon** [comment]
Thanks for the suggestions @abhinavdahiya, those will go a long way. I'd be happy for this to be closed now if there's nothing more to consider.

**Comment by abhinavdahiya** [comment]
> Thanks for the suggestions @abhinavdahiya, those will go a long way. I'd be happy for this to be closed now if there's nothing more to consider.

Thanks!

/close
