### ISSUE TITLE
Disable caching of bootstrap certificates or provide option to clean up install

### ISSUE THREAD

**Issue by andreasottosson** [openshift/installer#3635]
# Version

```console
$ openshift-install version
4.4.4
```

# Platform:
All

# What happened?
Installation using the same folder fails due to expired certificates if hidden file .openshift_install_state.json is not deleted.

# What you expected to happen?
If installation fails or completes why not remove this caching of certificates as this creates a lot of confusion. These certs are short lived so why not regenerate new ones each time to avoid issues.

# How to reproduce it (as minimally and precisely as possible)?

Run for example "openshift-install create ignition-configs", lets pretend this install fails. The next day you change a few things in install-config.yaml and run this command again. The installer then uses cached certificates from .openshift_install_state.json and you will be swearing until you find out why your install fails ;) This happened to both me and @jomeier today funny enough.

# Anything else we need to know?

Either we document this well, can't find any references to this in the docs. Or disable the caching of certificates or perhaps provide something like "openshift-install clean" to make sure we can start over. It is not hard do delete the file .openshift_install_state.json but since it is hidden it could confuse users.

# References

- #3502

**Comment by jomeier** [comment]
Today we changed the proxy and mirror information in the install-config.yaml and were surprised that it had no effect at all.

Then we discovered that a hidden .openshiftstate anything file contained old information from a former version of the install-config.yaml. 

Similar case as the one Andreas has described.

This is rather annoying because there is no obvious hint that cached Information is used.

What is this cache file good for? Because in IPI case the installer complains as soon as he finds Terraform state files. So repeatedly calling the installer is not possible at least in this case.

Could it be removed or a warning printed at least if it exists?

Greetings, Josef

**Comment by andreasottosson** [comment]
So I did find some text about this in the docs  under https://docs.openshift.com/container-platform/4.4/installing/installing_vsphere/installing-vsphere.html#installation-initializing-manual_installing-vsphere but still, could this not be done nicer? At least a warning as @jomeier said.
