### ISSUE TITLE
OpenShift Installer does not work with pre-provisioned DNS-entry in AWS

### ISSUE THREAD

**Issue by krathow** [openshift/installer#3657]
# Version
Latest OpenShift installer 4.4

# Platform:
aws

# What happened?

OpenShift cannot be installed due to a Terraform error with DNS Route53 as the public zone is pre-provisioned.
Setup is:
1) Within DNS-master AWS-Account we've got in Route53:      example.com (public zone)
2) within OpenShift AWS-Account we've got in Route53:           ocp4.example.com (public zone)
3) The DNS-Master account has a NS-record in example.com for forwarding DNS-queries to ocp4.example.com
--> this setup works fine

Now when we start the latest OpenShift installer, the installer fails because it cannot create the entries for ocp4.example.com in example.com

FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "Common Manifests": failed to generate asset "DNS Config": getting public zone for "example.com": No public route53 zone found matching name "example.com"

**Is there a switch for Terraform to not try to create an entry as it already pre-exists?**

# What you expected to happen?

Installer should have a switch to ignore the creation of Zone entries if they already pre-exist

**Comment by abhinavdahiya** [comment]
I think you are using `example.com` as basedomain.
You should be using `ocp4.example.com`

> failed to generate asset "DNS Config": getting public zone for "example.com": No public route53 zone found matching name "example.com"

That error is pretty clear what validation is failing. There should be a validate public r53 zone for the basedomain of the cluster.

**Comment by krathow** [comment]
Hello,
thank for your answer.
Sure this would work if we would use ocp4.example.com as basedomain,
creating an ugly long name:  mycluster.ocp4.example.com
Also, we cannot transfer the basedomain to the AWS-Account for Openshift.

Basically validation is failing because the installer does not recognize that there is already a valid domain for the cluster to put its records in, which can be easily achieved as a Terraform check like this:

`data "aws_route53_zone" "selected" {
   name         = "ocp4.example.com."
   private_zone = false
}`

if count = 0 create the public zone as usual, else work with the zone

**Comment by abhinavdahiya** [comment]
> Hello,
> thank for your answer.
> Sure this would work if we would use ocp4.example.com as basedomain,
> creating an ugly long name: mycluster.ocp4.example.com
> Also, we cannot transfer the basedomain to the AWS-Account for Openshift.
> 
> Basically validation is failing because the installer does not recognize that there is already a valid domain for the cluster to put its records in, which can be easily achieved as a Terraform check like this:
> 
> `data "aws_route53_zone" "selected" { name = "ocp4.example.com." private_zone = false }`
> 
> if count = 0 create the public zone as usual, else work with the zone

We never create public zone, and we are not going to too.. because creating public zone requires delegation with Domain Registrars.

Zone1: example.com (acct root)
Zone2: ocp4.example.com (acct openshift)

installer inputs: basedomain= example.com , clustername=mycluster

we want the installer to create
`api.mycluster.exmaple.com` and `*.apps.mycluster.exmple.com` records in Zone2 ??
^^ that doesn't seem right since Zone2 is only resp for `ocp4.example.com` subdomain??

**Comment by krathow** [comment]
Hello,

you're right about the public zone, my fault.

But what we want to achieve:
[1] Zone1: example.com (acct root - public zone)
[2] Zone2: ocp4.example.com (acct openshift - public zone)

installer inputs: basedomain= example.com , clustername=ocp4

so the installer should create:
`api.ocp4.example.com` and `*.apps.ocp4.example.com` 

which is fully within the installer's and AWS-accounts control.

So there should be a recognition or field to avoid checking if the public zone [1] is within the same account.

**Comment by abhinavdahiya** [comment]
> So there should be a recognition or field to avoid checking if the public zone [1] is within the same account.

For installer provisioned workflows `create cluster` that have publishing strategy External (default) we cannot skip the validation `there exists a public route53 zone for basedomain in the account where the cluster is being installed` because we need to control what records exists i.e create a record and point them to LBs created. It's not just the installer but other cluster operators in the cluster.

If you want to control these details, feel free to use the user-provisioned-workflow documented in https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-user-infra.html

**Comment by krathow** [comment]
ok alright, thanks for your help
