### ISSUE TITLE
examples directory still used though it's removed from the repo

### ISSUE THREAD

**Issue by ashcrow** [openshift/installer#368]
## Versions
06a4afb0a325db1b674ee69dc44321f5d03efd41

### What happened?
The following still reference `examples/` which is no longer available:

- https://github.com/openshift/installer/blob/67c75faf001d883fe8b4945d46624afaaaf2792a/tests/run.sh#L84
- https://github.com/openshift/installer/blob/d628b1ce3c76298e85af746bf7b20f440a0942cd/docs/dev/libvirt-howto.md#L166

### What you expected to happen?

If `examples/` is needed it should be in the repo (or a reference on how to get it should be available). Otherwise, the references to `examples/` should be removed.

### How to reproduce it (as minimally and precisely as possible)?

Look at the files :-D

**Comment by wking** [comment]
I've updated the docs in #369.

Updating `tests/` will be more difficult, because the smoke tests currently assume Bazel, and we dropped our remaining Bazel bits last night in #342.  It would be nice to drop our `tests/smoke` completely, and possibly just update `tests/run.sh` to use the end-to-end suite we currently use in CI.

**Comment by crawford** [comment]
This has since been fixed.

/close
