### ISSUE TITLE
[openstack][question] can we switch to other storage backend other than cinder/swift

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#3754]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform: openstack

IPI

# What happened?

https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md#image-registry-requirements 

it mentioned either swift or cinder will be used as image registry backend, however, is there any possibility to allow the image backend to be something like `nfs` so that we can get more flexibility ?

for example, in UPI, it allows to edit ` oc edit configs.imageregistry.operator.openshift.io/cluster` so that we can switch to other backend

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by Fedosin** [comment]
Short answer is Yes, but not in IPI.

Now, when you deploy a cluster on OpenStack, Image Registry Operator checks if Swift is available and the user has required permissions to write data there. If everything is okay, the operator uses the Swift driver to creates an image registry container there. https://github.com/openshift/cluster-image-registry-operator/tree/master/pkg/storage/swift 
Otherwise, it takes the PVC driver and provisions a Cinder volume that will be used as a backend for the image registry instance. 
https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/operator/bootstrap.go#L81-L94
https://github.com/openshift/cluster-image-registry-operator/tree/master/pkg/storage/pvc

It means that you can reconfigure the PVC driver with `oc edit configs.imageregistry.operator.openshift.io/cluster` and specify any other precreated PV there, either RWO or RWX.

Regarding to NFS and other shared filesystem things... In OCP 4.5 we are going to introduce Manila CSI driver operator, which will allow our users to provision RWX PVs using OpenStack Manila Service. https://github.com/openshift/csi-driver-manila-operator
You can take a look at these demos to see how it works:
https://asciinema.org/a/335725
https://asciinema.org/a/335729
If all goes well, then in 4.6 we will add Manila support to Image Registry Operator, and RWX (nfs or cephfs) volumes will be available in IPI mode there.

**Comment by jichenjc** [comment]
Thanks, I got what I want to know especially
```
It means that you can reconfigure the PVC driver with oc edit configs.imageregistry.operator.openshift.io/cluster after the installation and specify any other precreated PV there, either RWO or RWX.
```

this is really helpful ,so we will see how we can patch the IPI installed cluster 


for the Manila CSI driver, is it based on https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md or something else? just for reference perspective, also, from the demo seems the ceph is used ,so assume the target consumption backend is OCS?

**Comment by Fedosin** [comment]
Yes, you are right! It is based on https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md 
Manila CSI operator installs, configures and manages the lifecycle of Manila CSI driver from `cloud-provider-openstack` repo. We have tested it with `cephfs` and `nfs`, so they will be supported in 4.5.

**Comment by jichenjc** [comment]
thanks for the info, really appreicate your help~
