### ISSUE TITLE
Install on Mirantis Openstack

### ISSUE THREAD

**Issue by ayaseen** [openshift/installer#3841]
# Version

```console
$ openshift-install version
4.4 and later
```

# Platform:
Openstack Mirantis

# What happened?

We have a small issue, openshift through ansible playbook use security tags which do not exist.
How can we successfully install openshift with OpenStack Or procedures to integrate with openstack older than Queen?

**Comment by mandre** [comment]
Hi @ayaseen, we're targeting Queens as the minimal required OpenStack version because that's the oldest version we test against. From the top of my head, we're not requiring any feature introduced in Queens so it is very possible to have openshift run on older version with little or no effort. We'll gladly accept patches allowing the installer to deploy OpenShift to older OpenStack releases.

Let us know if you see a requirement that is not covered in https://github.com/openshift/installer/tree/master/docs/user/openstack#openstack-requirements

**Comment by ayaseen** [comment]
Hello,

Just I want to add one thing, we use contrail 4.1, I guess is not support the security tag feature.
How can we pass this requirement?
