### ISSUE TITLE
Enhancement: Using Azure Storage V2 in IPI (for internal image registry)

### ISSUE THREAD

**Issue by mohamedsaif** [openshift/installer#3858]
# Version
4.3.x

# Platform:
Azure

* IPI

# What happened?

Currently the IPI creates Azure storage accounts to be used by the cluster (specially the internal image registry).

Currently the storage account provisioned is v1, which is limiting for customers wishing to disable the public access to the storage account and enable the private endpoint, which is not supported in v1.

I tried to provision a new v2 storage account with private endpoint, then I updated successfully the secrets and configs of the image-registry-operator to point at that account and the operator started using the new storage account with no problem.

My ask is, why not use v2 storage account from the start to allow customers access the latest capabilities available.

Thanks.

**Comment by abhinavdahiya** [comment]
It's better you open this rfe with image registry operator https://github.com/openshift/cluster-image-registry-operator/issues

Installer itself is not responsible for creating this.

**Comment by link-webcreations** [comment]
For me the Storage account is created (here)[https://github.com/openshift/installer/blob/master/data/data/azure/main.tf#L137]
The kind of storage account is not specified, so it take the default one.
By using the (Azurerm provider)[https://github.com/openshift/installer/blob/master/go.mod#L123] in version v1.40.1, the default kind is StorageV1.

In order to solve this issue, it can help to either :

- Upgrade azurerm provider to v2.xxx
- Update terraform `main.tf` in this repo to specify the kind of storage account.
