### ISSUE TITLE
Openstack Parameter for Bootstrap Floating IP 

### ISSUE THREAD

**Issue by digglife** [openshift/installer#4192]
# Version

```console
$ openshift-install version
openshift-install 4.5.8
built from commit 0d5c871ce7d03f3d03ab4371dc39916a5415cf5c
release image quay.io/openshift-release-dev/ocp-release@sha256:ae61753ad8c8a26ed67fa233eea578194600d6c72622edab2516879cfbf019fd
```

# Platform:
Openstack UPI

# What happened?

Bootstrap Floating IP is automatically created and destroyed.

# What you expected to happen?

I need a parameter in `install-config.yaml` to assign a Floating IP address for Bootstrap Instance. The IP addresses in my public network do not all has the permission to access internet due to the security restriction of our company . So if it's automatically created there is a great chance that the bootstrap is not able to pull images successfully from internet.

I know it's a rare case, but I think being able to specify the floating IP for bootstrap like we already did for API/Ingress is a good function anyway. If it's OK I would like to implement it.

# How to reproduce it (as minimally and precisely as possible)?

N/A

# Anything else we need to know?

N/A

# References

N/A

**Comment by mandre** [comment]
/label platform/openstack
/close

The bootstrap floating IP is just convenience for you to retrieve the logs from the bootstrap node in the event the deployment fails at the bootstrap stage. It is unrelated to pulling container images on the bootstrap node.

You may want to [use a proxy](https://github.com/openshift/installer/blob/master/docs/user/customization.md#proxy) have a look at the installation on restricted networks. Note that we support installation on restricted networks for OpenStack platform since 4.3 but the documentation is [still in the works](https://github.com/openshift/openshift-docs/pull/22478). You can find a rendered version of the WIP documentation at https://osp-restricted-ipi-osdocs1021--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-restricted.html.
