### ISSUE TITLE
[Openstack] support RWX with cinder multiple attach ?

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#4425]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform:

openstack

# What happened?
https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md#image-registry-requirements
stated if we go PVC ,then only RWO is supported

with https://docs.openstack.org/cinder/latest/reference/support-matrix.html#driver-support-matrix
we can see actually multi attach is supported by a set of drivers
if multi attach can be configured and supported, whether it's possible to go RWX so that with out swift
still can run multiple image registry ? 

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by tombarron** [comment]
rwx should not be allowed for cinder (even with multi-attach) in the default *mount* volumeMode. *raw block* volumeMode must be used so that node-local filesystem like ext4 or xfs is not set up on the block device.  Then if the cinder back end supports multi-attach it can be *attached* to multiple k8s nodes without any file system being mounted on those nodes.
I'd have to know more about the intended use case for image registry better to comment on that but note that even mounted read-only node-specific fileystems are not safe for mounting on multiple nodes since metadata for the filesystem still needs to be controlled by a single node only.

**Comment by jichenjc** [comment]
>>>still needs to be controlled by a single node only.

I don't know this is true .. I think the volume is formatted and can be used by multiple instance (pods)? 
and metadata is in the volume itself and multiple pods see same info? I don't know the metadata here is the file system super block?

**Comment by tombarron** [comment]
The position of the upstream Cinder community has been that multi-attach volumes should be used either with (1) applications that work with raw blocks rather than file system paths (some databases do this,  or booting iso images for example), or (2) *clustered* file systems like GPFS, Veritas, etc..
#1 aligns with raw block volumeMode.
Unless I'm out of date, #2 is not available with k8s and traditional mount volumeMode since the choices for file system type are all node local like ext4 and xfs rather than the clustered filesystems.

The issue with file system metadata as I understand it is that multiple nodes will try to update the metadata and those file systems are not designed for that.  Here's one [discussion](https://unix.stackexchange.com/questions/68790/can-the-same-ext4-disk-be-mounted-from-two-hosts-one-readonly) of this issue.  Also, node-local journaling filesystems aren't designed to keep journals consistent across multiple nodes.

It could be that my understanding is out of date, in which case it would be good to cite more recent research results to show that mounting node-local filesystems on multiple nodes is safe.

**Comment by jichenjc** [comment]
@tombarron thanks for the info, will check more here and provide comment, might need some time, appreciate the help and info here
