### ISSUE TITLE
Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://************:6443/version?timeout=32s": dial tcp 20.56.106.54:6443: i/o timeout

### ISSUE THREAD

**Issue by mhassan-786** [openshift/installer#4676]
# Version

```console
$ openshift-install version
<4.6>
```

# Platform:

IPI azure

# What happened?

Enter text here.
Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://***********:6443/version?timeout=32s": dial tcp 20.56.106.54:6443: i/o timeout

# What you expected to happen?

Successful cluster running 

# How to reproduce it (as minimally and precisely as possible)?
./openshift-install create cluster --dir=. --log-level=debug

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by staebler** [comment]
There is not enough information to go on here. Did the installer capture logs from the bootstrap machine? There should be a message towards the end of the installer output like `Bootstrap gather logs captured here: <some tar gz>` that points you to the logs. Look in the logs to see what the output is from release-image.service and bootkube.service. The logs will be under bootstrap/journals in the log bundle.

**Comment by mhassan-786** [comment]
Thank you so much staebler. i will check it and let you know.

**Comment by mhassan-786** [comment]
[bootkube.txt](https://github.com/openshift/installer/files/6027222/bootkube.txt)

These are the logs from bootstrap/journals/bootkube.log

**Comment by mhassan-786** [comment]
#
[bootkube.txt](https://github.com/openshift/installer/files/6027225/bootkube.txt)


These are the logs from bootstrap.journals/bootkube.log

**Comment by mhassan-786** [comment]
[kubelet.txt](https://github.com/openshift/installer/files/6027245/kubelet.txt)


these are the logs from kubelet.log.

here i am totally confused how to fix it.

**Comment by staebler** [comment]
From the bootkube.txt, the bootstrapping is waiting for the necessary pods to be running on your control plane machines. Can you share your install-config.yaml and the control plane folders from your gather bundles?

**Comment by waveywaves** [comment]
Hi team I am facing a similar issue with the same problem. 
@staebler here is my bootkube.txt, hope it helps
[bootkube.log](https://github.com/openshift/installer/files/6033847/bootkube.log)

**Comment by staebler** [comment]
@waveywaves Your bootkube log is empty, implying that the bootkube service never ran. Check the logs from the release-image service. You are likely having an issue pulling images.

**Comment by bparrill** [comment]
I'm having a similar issue.  Tried with both 4.7 and 4.5 installers.  It gets near the end and fails:

INFO Waiting up to 20m0s for the Kubernetes API at https://api.mcm-garage-poc.mcmgaragepoc.com:6443...
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.mcm-garage-poc.mcmgaragepoc.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp: lookup api.mcm-garage-poc.mcmgaragepoc.com on 10.0.0.2:53: no such host
INFO Pulling debug logs from the bootstrap machine
INFO Bootstrap gather logs captured here "/home/bill/ocp_inst/~/ocp-install-1/log-bundle-20210405180742.tar.gz"
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://api.mcm-garage-poc.mcmgaragepoc.com:6443/version?timeout=32s": dial tcp: lookup api.mcm-garage-poc.mcmgaragepoc.com on 10.0.0.2:53: no such host

I can see the private DNS zone created with the api...com address pointing to the load balancer, so I'm not quite sure why that lookup is failing.  I'm doing an installer provisioned installation, so the only thing I've created beforehand was the DNS zone and the principal ID.

Here's a bootkube.log file from one of the attempts.  Any help would be greatly appreciated.

[bootkube.log](https://github.com/openshift/installer/files/6266425/bootkube.log)

**Comment by staebler** [comment]
@bparrill What are you using to resolve the mcmgaragepoc.com domain? As far as I can tell, that is not a publicly owned domain. You are getting `lookup api.mcm-garage-poc.mcmgaragepoc.com on 10.0.0.2:53: no such host` because your DNS server does not know how to resolve the domain. The DNS zone that you created beforehand for mcmgaragepoc.com is only useful if that domain is actually registered somewhere.

**Comment by bparrill** [comment]
Thanks @staebler .  Yes, that was the problem.  Going through an install now, but I had created a DNS Zone but hadn't created the top level domain.  Created one via the Azure app service domain and will try again.  Did some testing using nslookup and now it should resolve properly.

**Comment by anraghun** [comment]
@staebler I'm facing the exact issue  @bparrill was facing. I had just created a dns zone and ran the installer. As part of the IPI, I can see multiple public IP addresses created. What are they used for? Is any one of them used for the apiserver? If so, can't the lookup be done directly using the public IP instead of having to setup a domain name?

**Comment by staebler** [comment]
No, there is no provision for using the load balancers IP address in the public API URL. You do not *need* to use the public API URL, however. The cluster installation will proceed in cluster even if your public API URL is inaccessible. You could check on the state of the installation from another host that you create in the VPC or by connecting to the bootstrap host via SSH. Finally, you *could* connect to the API server via the load balancer's IP, but you would have to ignore certificate errors, since the server's certificates would not include the load balancer's IP in its domains.

**Comment by tambuta** [comment]
This is related to not having the DNS settings correct. 

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html#decide-procedure-create-subdomain

create a hosted zone which has a subdomain of  a registered domain. Get the name servers and have the registrar of your domain configure your domain with the name servers from AWS. After a 'whois' command with your subdomain, it will be clear whether or not your install will work. Ifr there is 'no match', bootstrapping will fail.
