### ISSUE TITLE
Enhancement: Verify installation images via hash before installation

### ISSUE THREAD

**Issue by ashcrow** [openshift/installer#475]
# Version

8404284

# Platform (aws|libvirt|openshift):

All

# What happened?

A developer attempted to install with a corrupted installation medium. The end result was a belief that the official OS image was broken.

# What you expected to happen?

It would be ideal if there was some kind of a check on a hash to verify the medium before it's used. EG: `sha1sum` verification.

# How to reproduce it (as minimally and precisely as possible)?

1. zip up a valid OS image
2. Install with the zip'd image as if it was not zipped
3. See that it got all the way to the point of bringing up the new hosts but fail to boot

# Anything else we need to know?

This is a feature request :-)

# References
- https://github.com/openshift/os/issues/361

/cc @dustymabe @cgwalters

**Comment by wking** [comment]
> It would be ideal if there was some kind of a check on a hash to verify the medium before it's used. EG: `sha1sum` verification.

Once we get that far, I think we might as well to OpenPGP verification as well.  Are there plans for signing hashes for the compressed and/or uncompressed images?  Ideally both, because then we could verify the signature before going through the work of uncompressing, and we could verify the signature again when we come through and reuse a cached, uncompressed image.

**Comment by ashcrow** [comment]
Related: https://github.com/openshift/os/issues/362

**Comment by eparis** [comment]
I do not believe that the openshift installer is going to do anything in this area in the short/medium term and so I am closing this issue. I apologize for the inconvenience.
