### ISSUE TITLE
coreos-bootimages releaseVersion not substituted

### ISSUE THREAD

**Issue by cgwalters** [openshift/installer#4797]
Just launched `4.8.0-0.nightly-2021-03-26-123311` and I noticed that 
```
$ oc -n openshift-machine-config-operator get -o yaml configmap/coreos-bootimages | head
apiVersion: v1
data:
  releaseVersion: 0.0.1-snapshot
  stream: |
    {
      "stream": "rhcos-4.8",
      "metadata": {
        "last-modified": "2021-03-24T13:05:37Z"
      },
      "architectures": {
...
```

Not sure yet why `releaseVersion` isn't substituted.  It's the same approach as [this key in the MCO](https://github.com/openshift/machine-config-operator/blob/041b9665b013422ad1459e0f2f8c765aee073089/install/0000_80_machine-config-operator_05_osimageurl.yaml#L11).

Not urgent but would be good to fix because it will allow an operator to wait until the configmap synchronizes with the expected cluster version.

**Comment by wking** [comment]
The `0.0.1-snapshot` replacement is something that [`oc adm release new ...` does to incoming manifests][1].  But #4760 should be injecting the new files as a CVO manifest.  So checking a recent nightly:

```console
$ oc adm release extract --to manifests registry.ci.openshift.org/ocp/release:4.8.0-0.nightly-2021-04-01-213116
$ wc manifests/0000_50_installer_coreos-bootimages.json
    0   678 24490 manifests/0000_50_installer_coreos-bootimages.json
$ cut -b-80 manifests/0000_50_installer_coreos-bootimages.json
{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"coreos-bootimages","na
```

So it's a single line of compact JSON, and lacking `oc`'s required leading `([\W]|^)`.  Probably better to write the file as YAML, instead of dumping it as JSON?  That would give you the leading whitespace.

[1]: https://github.com/openshift/oc/blob/bdd8f89997ce224cb6f186716c18bee872d3b318/pkg/cli/admin/release/image_mapper.go#L328-L334

**Comment by staebler** [comment]
Interesting. So it doesn't match the regex because it is wrapped in quotes. Seems easy enough to fix.

**Comment by wking** [comment]
For reasons I don't understand, #4814 doesn't seem to have fixed this.  I've filed [OCPBUGS-19824](https://issues.redhat.com/browse/OCPBUGS-19824) to track.
