### ISSUE TITLE
Need to create worker node with "IP Forwarding" enabled in GCP using openshift-installer

### ISSUE THREAD

**Issue by priyankash-citrix** [openshift/installer#4884]
# Version

```console
$ openshift-install version
./openshift-install 4.7.7
built from commit fae650e24e7036b333b2b2d9dfb5a08a29cd07b1
release image quay.io/openshift-release-dev/ocp-release@sha256:aee8055875707962203197c4306e69b024bea1a44fa09ea2c2c621e8c5000794
```

# Platform:
GCP
* IPI (automated install with `openshift-install`.)

# What happened?
`openshift-installer` creates worker node VM with "IP Forwarding" disabled by default in GCP.
Because of which the traffic destined to my pod network with gateway as worker node IP is getting dropped at node.

I can't see any configurable parameter in the docs to bring up cluster node VM with "IP Forwarding" enabled. Doc referred:
https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-customizations.html

GCP have a restriction that "IP Forwarding" for a VM can only be enabled while creating the VM. 
![image](https://user-images.githubusercontent.com/43474200/116356774-580fa080-a819-11eb-8871-bf0830dd447f.png)
This can be seen in the GCP doc here https://cloud.google.com/vpc/docs/using-routes#canipforward

So it can't be done manually after cluster creation, `openshift-installer` will have to do it while creating the cluster node VMs.

# What you expected to happen?
Some parameter should be provided in the `install-config.yaml` that can be used to enable the "IP forwarding" feature for the cluster node VMs. 

# How to reproduce it (as minimally and precisely as possible)?
Install an OpenShift cluster on GCP with default configuration.

```console
./openshift-install create cluster --dir=<installation_directory>
```

**Comment by staebler** [comment]
We make an effort to keep the options in the install-config.yaml to a minimum set that is useful for most users so that the install config does not become too unwieldy for users to work with. We will take into consideration whether enabling "IP Forwarding" is used by enough users to warrant inclusion. For now, however, we have no plans to add a field to the install config to toggle this.

You are always welcome to provision the infrastructure yourself in order to create machines that have "IP Forwarding" enabled. See https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-user-infra.html for one example of how to provision the infrastructure yourself.
