### ISSUE TITLE
Why do you need a private hosted zone? AWS UPI

### ISSUE THREAD

**Issue by dontlaugh** [openshift/installer#5065]
# Platform:
AWS UPI (user provided infrastructure)

My question concerns this: https://github.com/openshift/installer/blob/master/upi/aws/cloudformation/02_cluster_infra.yaml#L89-L102

Linked from the AWS UPI installation docs: https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md#create-dns-entries-and-load-balancers-for-control-plane-components

I'd like to manage all my DNS myself. Do I really need to create a private hosted zone for easy openshift cluster?

**Comment by patrickdillon** [comment]
Private zones are utilized to provide split-horizon DNS so that the cluster machines talk to the internal LB rather than going through the public internet to reach the external LB. We have future plans for cluster-hosted DNS so that private zones would not be needed. Until then, one option would be to create a private zone but delegate it to your DNS provider/ 

May I ask why you want to manage the internal DNS for the cluster? Are you prohibited from using the DNS provider of your cloud platform?

**Comment by dontlaugh** [comment]
We use route53, but we have a single hosted zone we'd prefer to set all the records in. 

I, for one, don't mind if public dns points to "private" IPs.

**Comment by patrickdillon** [comment]
Then you might be able to get away with just putting the api-int record in the public zone. You need to remove the private zone from the dns manifest so the ingress controller doesn't look for it. 

I have experimented with this on other platforms but not aws, and definitely not for a production environment.

**Comment by dontlaugh** [comment]
Thanks for the pointer. We are removing the dns zone according to this https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md#remove-dns-zones

Incidentally, I do appreciate that you all provide "bring your own infra" docs at all. I have some familiarity with the original Tectonic installer, and it required us to launch a new VPC for each cluster.
