### ISSUE TITLE
Allow AWS spot when creating cluster

### ISSUE THREAD

**Issue by ioniryonathan** [openshift/installer#5089]
# Version

openshift-install 4.7.19
built from commit 3948d1fe9f04057823b871133085d602e6575067
release image quay.io/openshift-release-dev/ocp-release@sha256:eafdac268e1f65053de423ba4a028e8de5133ab78e7954d76ed838bcf5f4f666

# Platform:

* AWS IPI

# What happened?

Allow spot creations from AWS customization to cluster yaml  and not from machineset manifest.

### What needs fixing?

# What you expected to happen?

Need a way to set spot instance (and maxprice) without having to modify machineset AFTER the cluster was created.

# How to reproduce it (as minimally and precisely as possible)?

# References

**Comment by ksingh7** [comment]
+1 to this feature 

It would be nice if openshift installer can provide a way to supply, under compute section to launch compute nodes on Spot at the time of cluster creation

```
providerSpec:
  value:
    spotMarketOptions: {}
```

**Comment by staebler** [comment]
You can accomplish this at the time of cluster creation by modifying the manifests for the worker machinesets.

**Comment by ioniryonathan** [comment]
This can only be done after bootstrap

**Comment by ioniryonathan** [comment]
It is ignored for masters. I get normal lifecycle nodes. Workers do create
as spots. But why via this cumbersome way?

**Comment by staebler** [comment]
> It is ignored for masters. I get normal lifecycle nodes.
OpenShift does not support spot instances for control plane nodes. The cluster cannot function reliably if the control plane nodes are subject to being reclaimed by AWS.

> Workers do create as spots. But why via this cumbersome way?
The install-config.yaml is intended to provide configuration that either must be done at install time or for which a large portion of the user base will take advantage of. The OpenShift installer provides access to the manifests for manual modification explicitly so that users can make their own customizations at install-time if they have unique configuration requirements. In this case, it is relatively easy to make the change post-installation, which is what the OpenShift team would recommend.
