### ISSUE TITLE
AWS : Allow adding additionnal SG to nodes in IPI

### ISSUE THREAD

**Issue by ThinkBriK** [openshift/installer#5265]
# Version
4.8

# Platform:
AWS IPI

# What happened?

Tried to use IPI with a proxy set but installation fails because we're using a specific SG to allow access to the proxy (it's one of the many cases that could occur).

It would be invaluable to allow an `additionnal_sg` parameter to the `install_config.yaml` in the aws platform section to allow adding securityGroups to the Bootstrap, Masters and Workers Nodes.

**Comment by staebler** [comment]
Unfortunately, it is unlikely that we will add the ability to specify an additional security group to the install config.

For the compute nodes, you can manually modify the `99_openshift-cluster-api_worker-machineset-XXX.yaml` manifests after running `openshift-install create manifest` to add your security group.

For the bootstrap and control plane nodes, you can either do a UPI install or modify the security groups for the AWS instances after the installer creates them.

**Comment by ThinkBriK** [comment]
Thank you, I already had the same workaround implemented but it's not optimal, especially when it comes to upgrade the cluster.

**Comment by staebler** [comment]
> Thank you, I already had the same workaround implemented but it's not optimal, especially when it comes to upgrade the cluster.

What are you having to do when you upgrade the cluster?

**Comment by gswallow** [comment]
I would like to throw an upvote into this issue.  I'm hitting the same issue because I'm installing from a machine outside of the VPC in which I'm creating a private cluster, and the installer fails when it can't reach the internal API endpoint.

It would be nice to be able to add a security group to the list of security groups applied to workers, masters, and the API.  Meanwhile, I'll run with the hint earlier in this thread and see if I can adjust a manifest.
