### ISSUE TITLE
failed to fetch dependency of "bootstrap ignition config" AWS credentials provided by EC2RoleProvider are not valid for default credentials mode

### ISSUE THREAD

**Issue by joekozhaya** [openshift/installer#5512]
# Version

```console
$ openshift-install version
./openshift-install 4.8.13
built from commit 450e95767d89f809cb1afe5a142e9c824a269de8
release image quay.io/openshift-release-dev/ocp-release@sha256:5d396ad7d5f3cb527580c735e87dfd3b853bbb531e7f03e3a184d0accc223cdf

```

# Platform:

# What happened?
Installer fails to generate Openshift Manifests giving the error
failed to fetch dependency of "Metadata": failed to fetch dependency of "Bootstrap Ignition Config": failed to generate asset "Openshift Manifests": AWS credentials provided by EC2RoleProvider are not valid for default credentials mode

# What you expected to happen?

Was expecting Manifests to be generated.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./openshift-install create cluster --dir=/workdir/ocp48 --log-leve=debug
```

# Anything else we need to know?

We suspect the error may be because of IAM permissions; however, we reviewed the permissions referenced in the documentation and confirmed the IAM user has such permissions.
Can you help us understand what exactly is the installer trying to do with this step? and what exact step fails? is it checking some IAM permissions? or is it trying to create some AWS resources and if so, which ones?

# References

None

**Comment by staebler** [comment]
You are using the IAM role associated with the EC2 instance on which you are running the installer. That IAM role cannot then be given to the OpenShift cluster to be used, since the OpenShift cluster will be running on different EC2 instances. You must provide explicit credentials for an IAM role that is independent of the EC2 instance.

Alternatively, you can use the manual credentials mode for the cluster. See https://docs.openshift.com/container-platform/4.9/installing/installing_aws/manually-creating-iam.html#manually-creating-iam-aws.
