### ISSUE TITLE
Installer throws out Terraform crash dumps

### ISSUE THREAD

**Issue by crawford** [openshift/installer#575]
Unfortunately, Golang and Terraform don't use the well-established crashdump mechanisms provided by Linux. Instead, it writes `crash.log` into the current working directory which is subsequently thrown away by the installer.

**Comment by wking** [comment]
Docs [here][1].  Have we been panicing Terraform?

[1]: https://www.terraform.io/docs/internals/debugging.html#interpreting-a-crash-log

**Comment by crawford** [comment]
I ran into one yesterday when I waa testing out AWS NLBs. Turns out, the AWS provider we are using is really old. Bumping it fixed that particular panic.

**Comment by wking** [comment]
I'm going to close this, since vendoring Terraform (#822) and its plugins (#919) should help address the "really old provider" issues.  And testing out new Terraform modules is a dev-only thing, so we can always jump through some hoops to keep `crash.log` (e.g. commenting out the deferred `os.RemoveAll`).  But feel free to re-open if that's not convincing ;)

/close
