### ISSUE TITLE
Version Dependencies Document.

### ISSUE THREAD

**Issue by droslean** [openshift/installer#589]
Related also with #477 

Can you provide the list of the dependencies that are required to use the `openshift-installer`

It is unclear which versions of the dependencies are required.
In addition, can you provide a way to find those dependencies? 
Example: repository CDN or rpm link.

**Comment by wking** [comment]
> Can you provide the list of the dependencies that are required to use the `openshift-installer`

We list build deps [here][1], although it's a bit thin on versions.  That's mitigated by [this][2], which indirectly declares version numbers and a potential download location for the whole userspace.  Having min versions in Markdown would still be nice, but seems low priority.

*Runtime* deps are a different beast.  Most users won't need them, because our only userspace dep is Terraform, and we declare a version [here][3] (but will probably work with any recent Terraform).  Libvirt (QEMU/KVM), on the other hand, is a deep host stack, where you had issues in #477 (and see also #582, etc.).  Narrowing down acceptable versions would be great, but devs are likely to run recent-ish versions, and again, it's a lot of work. But pull requests are welcome :).

[1]: https://github.com/openshift/installer/blob/0ad5969b93909a06e4ec7149926850233140436c/docs/dev/dependencies.md
[2]: https://github.com/openshift/installer/blob/0ad5969b93909a06e4ec7149926850233140436c/images/installer/Dockerfile.ci#L4
[3]: https://github.com/openshift/installer/blob/0ad5969b93909a06e4ec7149926850233140436c/hack/get-terraform.sh#L25

**Comment by crawford** [comment]
We've since removed many of the dependencies of the installer. If you can run `./openshift-install --version` successfully, you have all of the runtime dependencies for creating an AWS cluster.

/close
