### ISSUE TITLE
updating failed

### ISSUE THREAD

**Issue by moalghwell** [openshift/installer#5968]
After the installation finished and the "bootstrap" removed without intervention, the OpenShift didn't come up and the URL never worked (console-openshift-console.apps.<cluster name>.<domain name>). I issued the command "./openshift-install wait-for install-complete" the following are extractions from the errors:
Cluster operator authentication Degraded is True with ...
....    number
...       of
...    degraded systems
Cluster operator ingress Degraded is True with IngressDegraded: ...
Cluster operator monitor Degraded is True with MultipleTasksFailed: ...
...  number
...    of
...   updates errors
FATAL failed to initialize the cluster: Some cluster operators are still updating:  authentication, console, ingress, monitoring

# Version

```console
$ openshift-install version
./openshift-install 4.10.15
built from commit ...
release image quay.io/openshift-relaese-dev/ocp-release@sha256:...
release architecture amd64
```

# Platform:

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by patrickdillon** [comment]
There is not enough information in this issue to be actionable. Platform is not specified. From the little information provided, the ingress operator did not become available, so that would explain other failures. Read the troubleshooting guide here https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md and check things out, particularly whether your compute nodes are healthy.

Feel free to reopen when you can provide more information, but I am closing this as it does not provide any useful feedback on the installer.

/close
