### ISSUE TITLE
Install openshift on Centos

### ISSUE THREAD

**Issue by cuttingedge1109** [openshift/installer#6073]
I used to deploy OKD clusters on UPI(Openstack) using installer referring to this guide https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md. It requires Fedora Core OS.
But now I want to install OKD clusters on Centos 8.
How can I realize this?

I found that installer generates ignition files for bootstrap, master and worker machine/machinesets and use them as userdata. It seems likely centos doesn't recognize ignition file properly.
I am planning the following approaches;
- Rebuild centos 8 image which knows ignition 
- Convert ignition file to cloud-init which centos can analyze
Are these feasible? I want your advice.
Regards.

**Comment by bshephar** [comment]
Hey,

I honestly don't think there is much desire or need to do this tbh. The entire platform is built around CoreOS as the central underpinning of OpenShift. Even the downstream productised OpenShift product doesn't support RHEL as an OS option. It's only CoreOS. CoreOS gives us the ability to keep the platform ephemeral and provide stability. I'm really not sure what use-case or reasoning there would be to change the fundamental design of the machine config mechanism in order to support CentOS. 

To directly answer your question. I don't really think this would be feasible.

I see it has been 20 days since you opened this. So I just wanted to share some feedback and let you know that this is fairly unlikely to be supported. Hopefully that explanation provides some insights as to the reasoning for sticking with Fedora CoreOS over CentOS.

**Comment by barbacbd** [comment]
@cuttingedge1109 If you desire RHEL hosts you can/should look into openshift ansible. It takes a bit more setup, but this may be closer to your end goal.

**Comment by bshephar** [comment]
Maybe this is what you're after:
https://cloud.redhat.com/blog/okd-streams-building-the-next-generation-of-okd-together

CentOS Stream CoreOS, or SCOS:
https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/dashboards/overview#4-scos-stable
