### ISSUE TITLE
libvirt: List recommended OS'

### ISSUE THREAD

**Issue by raesene** [openshift/installer#693]
If possible, it'd be great to list what base operating systems are supported/recommended for the libvirt install, as at the moment it doesn't feel too self-evident.

If people are trying out the installer from the main README, which is likely as the okd.io site has stopped recommending the old install method, then they're going to get frustrated hitting unusual errors on what would seem to be obvious OS choices.

I've been trying an install with fully updated CentOS7 and hitting multiple areas where the software versions are not high enough for the install to complete (e.g. golang, qemu), so seems like that's not a good option, but it's not clea what a better option would be.

**Comment by wking** [comment]
> If people are trying out the installer from the main README, which is likely as the okd.io site has stopped recommending the old install method, then they're going to get frustrated hitting unusual errors on what would seem to be obvious OS choices.

The main README is mostly for AWS (and eventually OpenStack and other end-user platforms).  Libvirt is intended to be dev-only (maybe we should remove it from "Supported Platforms", @abhinavdahiya, @crawford?  I'd understood it to be "best-effort, but we'll try and keep it working for convienience"), and the main README links [the libvirt docs][1].  There have been a number of requests to tighten down version and dependency information for libvirt (#455, #690, etc.), but I've been holding off until we get get CI coverage for libvirt (so we can test the versions we assert will work).

On the Go front, there's previous discussion in #619 and #621.  We support all Go versions that the upstream Go project continues to support.  It's not clear to me what happens on OSes who fall behind Go's... progressive?... support policy.  Are there distro-specific folks who continue to find, monitor for, and backport/patch security issues (like the long-term kernel folks)?  How about having `build.sh` taking Go errors and printing something like:

    Try building this in a container using:

      podman build -tag installer -f images/installer/Dockerfile.ci .

since that Dockerfile is tested by CI, so we know it works.  In production, I expect most users will be using binaries we provide instead of compiling themselves, so it's not clear to me if it's worth a build matrix to exercise an extended range of dependencies.

[1]: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

**Comment by xsgordon** [comment]
There are newer qemu builds for CentOS7 (qemu-kvm-ev) you just need to enable the virt-common repo.

With regards to the libvirt provider being supported/usable or not the challenge is of it's not then there isn't really a direct replacement for oc cluster up right now for OKD (the get started button on the OKD website actually 404s right now because the oc cluster up docs were removed).

**Comment by wking** [comment]
> ... the get started button on the OKD website actually 404s right now because the oc cluster up docs were removed

What, they were linking straight to master?  We should get that link pointed at a specific tag/commit.  The libvirt setup has been reasonably reliable, but docs are still sparse and CI gating is still evolving (so with both RHCOS and OpenShift release images floating, things can and do still break every week or so).  I think we'll be in a much more stable place in a month or so, but we're certainly not at the `oc cluster up` level right now.

**Comment by raesene** [comment]
Thanks very much for the additional info, very useful :) Yesterday I was basically following through the process from the okd.io site starting with the 404 on the "getting started" link and hitting issues just following what's in the docs. at the moment.

sounds like my best bet for the time being (just building a demo cluster) is `oc cluster up`.

**Comment by zeenix** [comment]
We should list the OSs that it's been tested on in the docs, yeah.

**Comment by abhinavdahiya** [comment]
@zeenix is this something you are still looking at?

**Comment by abhinavdahiya** [comment]
> @zeenix is this something you are still looking at?

/close
