### ISSUE TITLE
Programatic Status on Install Process

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#705]
Request from Service Delivery who would like to have some insight into how far along the install process is to display to the user. 

Anyone have ideas on how this could be implemented, and when it might be viable to look into implementation?

CC @oourfali

**Comment by crawford** [comment]
I think we should continue down the path we have started with the `bootstrap-complete` event. We need to define a few install milestones and emit events when we reach those points. We can then use that to:

  1. indicate how far along the install has progressed
  2. benchmark the installation process and identify the slow steps
  3. estimate how much time is left in the installation

**Comment by dgoodwin** [comment]
This would likely make SD very happy, sounds promising. In further discussion it sounds like this doesn't have to be super high priority at this time.

**Comment by wking** [comment]
> We need to define a few install milestones and emit events when we reach those points.

This only works once you have enough of a cluster going to be able to submit events.  Before that, you have a few phases of connection errors while waiting for the API to come up, depending on whether the API connector hits the etcd-cert-signer-pretending-to-be-a-control-plane, the actually-useful-for-events bootkube control plane, or an intermediate state where nothing is listening on 6443 at all.  Are they interested in insight into those stages as well, because getting that information off the bootstrap node would require another channel (SSHing in and searching `bootkube.service` logs?).

**Comment by crawford** [comment]
For those earlier stages, we can make use of journal-gatewayd to stream the logs over to the installer. We should be able to annotate them enough so that we aren't grepping through the logs for particular strings.

**Comment by eparis** [comment]
while this is a good idea, I do not think we are going to address it in the short/medium term. If this is important please feel free to open an issue in Jira, but I am going to close this issue.
