### ISSUE TITLE
Unable to create OKD cluster on openstack without router

### ISSUE THREAD

**Issue by alexanderbystrom** [openshift/installer#8494]
# Version

```console
$ openshift-install version
./openshift-install 4.14.0-0.okd-2023-11-14-101924
built from commit cebc8ab0fd6f8b66197f5a4e058ea4913dbb587c
release image quay.io/openshift/okd@sha256:72d40c51e7c4d1b9c31e9b0d276d045f1b2b93def5ecee49186df856d40bcb5c
release architecture amd64
```

# Platform:
Openstack

* IPI

# What happened?

When trying to install OKD in openstack with router quota set to 0 (router extension not enabled) the installer fails on the quota check. When you install a cluster without floating-ips and without a externalNetwork the installer should not create a router and the quota check is unnecessary.

Output from .openshift_install.log
time="2024-05-29T16:22:54+02:00" level=debug msg="  Generating Platform Quota Check..."
time="2024-05-29T16:22:54+02:00" level=fatal msg="failed to fetch Cluster: failed to fetch dependency of \"Cluster\": failed to generate asset \"Platform Quota Check\": error(MissingQuota): Router is not available because the required number of resources (1) is more than the limit of 0"

# What you expected to happen?

The installer should not care about the quota of routers since it's not supposed to create one.

# How to reproduce it (as minimally and precisely as possible)?

1. Have 0 routers in openstack qouta
2. Run openshift-install with platform.openstack.externalNetwork not set

# Ref

https://docs.okd.io/4.14/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-accessing-api-no-floating_installing-openstack-installer-custom

**Comment by mandre** [comment]
Hey @alexanderbystrom, not sure if you figured this out already but in order to install without the installer creating a router, you need to provide it with an existing (and usable) subnet:

https://github.com/openshift/installer/blob/release-4.14/docs/user/openstack/customization.md#custom-subnets

This should bypass the router quota check.

I'm closing this issue as I think it works as intended. Feel free to reopen if you're still having issues even with using custom subnet.
/close
