### ISSUE TITLE
Where is the public guide for openstack guys?

### ISSUE THREAD

**Issue by wjiangjay** [openshift/installer#855]
List pre-requirements and step to step guide.

Or openstack is still in progress?

**Comment by wking** [comment]
> Or openstack is still in progress?

CC @flaper87.  But yes, [still in progress][1].

[1]: https://github.com/openshift/installer/blame/v0.6.0/README.md#L7

**Comment by akostadinov** [comment]
Being experimental shouldn't mean we will not have instructions. How else can one try it and report issues?

there is already a stale doc pull request #796 about documenting OpenStack. I think also requirements around OpenStack version and object store availability also need to be documented.

**Comment by wking** [comment]
> Being experimental shouldn't mean we will not have instructions.

Agreed.  But it means "we don't think this is ready to go yet, expect to invest a fair bit of time to get it working", and that applies to doc scarcity as well as actual implementation limitations.

> How else can one try it and report issues?

Your issue here is a good start ;).  And the OpenStack folks have a lot on their plate, I dunno if it would be easier for them to take it from here, if it would be easier for them to review a `docs/user/openstack/README.md` or some such that you could submit.  Of course, you may not have time to work up the docs either ;).

As far as what goes into the docs, I the step-by-step configuration is handled fairly well by the interactive wizard (and its inline help).  It's still nice to call out pre-reqs so folks don't have to bother with the wizard only to realize partway through that they need an object store (or whatever) which they (for whatever reason) cannot provide.  But I don't know if it's worth sinking much time into "and then the wizard will prompt you for..." sorts of things.

I also think it's useful to [flesh out our godocs][1], for folks who skip the wizard and provide their own install-config (although see @crawford's counter-point [here][2]).

So there are a number of things we could do better on the doc front, and, as far as the OpenStack bits go, it's up to @flaper87 and company to lead us in whatever direction they think gets us there most efficiently :p.

[1]: https://github.com/openshift/installer/pull/796#issuecomment-446024738
[2]: https://github.com/openshift/installer/pull/796#issuecomment-446028255

**Comment by sferich888** [comment]
I agree the current state of using OpenStack here leaves a lot to be desired. The code to use OpenStack is either incomplete (likely given its experimental state), and or not documented enough to get a user through a full cluster install. 

While this Issue is pushing for document how people can create/deploy OCP to OSP. IE: Meet the pre-requisites. 

I want to ask why the installer does not first, sanity check the environment it's deploying to https://github.com/openshift/installer/issues/867 
If we did this the need for documentation would GREATLY be reduced as we could in code define all the steps a user needs to take to have a successful install. 

The other question I have is, are we simply at a point where we don't yet have the work done where https://github.com/openshift/installer/issues/874 is met? If so; thats fine but docs (like this request here) are needed to call out where we 'think' the big gaps are. This is not in an experimental state (it's in a draft - pre-alpha state).

**Comment by wjiangjay** [comment]
@wking Yeah, actually I draft this issue to make it clear with the openstack progress for community, since I did not see guys which have successful installation with openstack provider, but aws and libvirt got so many feedback.

**Comment by wjiangjay** [comment]
> I agree the current state of using OpenStack here leaves a lot to be desired. The code to use OpenStack is either incomplete (likely given its experimental state), and or not documented enough to get a user through a full cluster install.
> 
> While this Issue is pushing for document how people can create/deploy OCP to OSP. IE: Meet the pre-requisites.
> 
> I want to ask why the installer does not first, sanity check the environment it's deploying to #867
I agree this, if we can check before we create resources, it a better UX, since destroy always met various scenarios, and can not make sure all will be success each time.
> If we did this the need for documentation would GREATLY be reduced as we could in code define all the steps a user needs to take to have a successful install.
> 
> The other question I have is, are we simply at a point where we don't yet have the work done where #874 is met? If so; thats fine but docs (like this request here) are needed to call out where we 'think' the big gaps are. This is not in an experimental state (it's in a draft - pre-alpha state).

**Comment by russellb** [comment]
See #904, where I've included some docs

**Comment by wking** [comment]
I'm closing as fixed by #904.  If you have specific concerns that are still not addressed in the new docs, please open a new issue.

/close
