### ISSUE TITLE
Error deleting VPC - hangs uninstall

### ISSUE THREAD

**Issue by coreydaley** [openshift/installer#963]
# Version

```console
$ openshift-install version
./bin/openshift-install ac006ae671a645553d58c8a29c676968dfa3d85f
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

time="2018-12-20T14:32:50-05:00" level=debug msg="deleting VPC: vpc-08983ed088effc7f9"
time="2018-12-20T14:32:50-05:00" level=debug msg="error deleting VPC vpc-08983ed088effc7f9: DependencyViolation: The vpc 'vpc-08983ed088effc7f9' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: ae5a12f8-5dff-4526-b349-1e0ad0a77b57"
time="2018-12-20T14:32:50-05:00" level=debug msg="Exiting deleting VPCs (map[openshiftClusterID:226b53e5-8e0c-418e-b473-ce68438afbde])"

# What you expected to happen?
VPC should be deleted correctly and removal should not hang
Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

create a cluster, and then delete it

**Comment by wking** [comment]
Sometimes this happens when an operator or other actor creates a resource that blocks VPC deletion but forgets to apply the appropriate tags to that resource (more on "the appropriate tags" in #465).  If you see it, we need to know which resource was blocking VPC deletion.  Hunting around in the AWS web console for resources which still exist in that VPC is a pain, but that may be what you need to do.
